server:
  port: 8080

logging:
  config: classpath:logback-spring.xml

etcd:
  servers: http://192.168.2.130:2379,http://192.168.2.131:2379,http://192.168.2.132:2379
  lockPath: /lock/stock

spring:
  redis:
    host: 192.168.2.10
    password: redis123